api-version: 1.16
main: me.magiccmax.magicctime.MagiccTime
name: MagiccTime
version: '1.0'
description: Time logger
load: POSTWORLD
author: MagiccMax
commands:
   playTime:
      description: shows your playtime
      usage: /playTime
      permission: magicctime.playtimeCMD